name: deepgram_speech_to_text
description: >
  A Deepgram client for Dart and Flutter, supporting all Speech-to-Text and Text-to-Speech features on every platform.
version: 4.0.1
repository: https://github.com/tempo-riz/deepgram_speech_to_text

topics:
  - deepgram
  - speech-to-text
  - text-to-speech
  - streaming
  - voice

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1
  universal_file: ^1.0.0
  wav: ^1.3.0
  web_socket_channel: ">=2.4.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
  will_it_run: ^1.0.4
